// auth action types
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT = "SIGN_OUT";

// weather action types
export const UPDATE_ERROR_MSG = "UPDATE_ERROR_MSG";
export const RESET_ERROR_MSG = "RESET_ERROR_MSG";
export const ADD_CITY_DATA_SUCCESS = "ADD_CITY_DATA_SUCCESS";
export const UPDATE_CITY_ITEM_WEATHER = "UPDATE_CITY_ITEM_WEATHER";
export const UPDATE_CITY_ITEM_WEATHER_FAILED =
	"UPDATE_CITY_ITEM_WEATHER_FAILED";
export const ADD_CITY_DATA_FAILED = "ADD_CITY_DATA_FAILED";
export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";
export const REMOVE_CITY_FROM_LIST = "REMOVE_CITY_FROM_LIST";
export const FETCHING_DEFAULT_WEATHER = "FETCHING_DEFAULT_WEATHER";
export const STOP_FETCHING_DEFAULT = "STOP_FETCHING_DEFAULT";
export const FETCH_ALL_WEATHER_DATA = "FETCH_ALL_WEATHER_DATA";
export const FETCH_ALL_WEATHER_DATA_FAILED = "FETCH_ALL_WEATHER_DATA_FAILED";
export const CLEAR_ALL_CITIES = "CLEAR_ALL_CITIES"
export const REFRESH_CURRENT_WEATHER = "REFRESH_CURRENT_WEATHER"

// user action type
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
