// auth action types
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_OUT = "SIGN_OUT";

// weather action types
export const ADD_CITY_DATA_SUCCESS = "ADD_CITY_DATA_SUCCESS";
export const ADD_CITY_DATA_FAILED = "ADD_CITY_DATA_FAILED";
export const CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG";
export const REMOVE_CITY_FROM_LIST = "REMOVE_CITY_FROM_LIST";
export const FETCH_DEFAULT_WEATHER = "FETCH_DEFAULT_WEATHER";
export const FETCH_DEFAULT_WEATHER_FAILED = "FETCH_DEFAULT_WEATHER_FAILED";
export const FETCHING_DEFAULT_WEATHER = "FETCHING_DEFAULT_WEATHER";
export const STOP_FETCHING_DEFAULT = "STOP_FETCHING_DEFAULT";
export const FETCH_FIVE_DAY_WEATHER = "FETCH_FIVE_DAY_WEATHER";
export const FETCH_FIVE_DAY_WEATHER_FAILED = "FETCH_FIVE_DAY_WEATHER_FAILED";
export const FETCH_ONE_DAY_FORECAST = "FETCH_ONE_DAY_FORECAST";
export const FETCH_ONE_DAY_FORECAST_FAILED = "FETCH_ONE_DAY_FORECAST_FAILED";
export const FETCH_ALL_WEATHER_DATA = "FETCH_ALL_WEATHER_DATA";
export const FETCH_ALL_WEATHER_DATA_FAILED = "FETCH_ALL_WEATHER_DATA_FAILED";
